Recipe Info:
    portion:
        Value: 4
    preparationtime:
        Value: 15
        Units: min
    bakingtime:
        Value: 5
        Units: min
    source:
        Value: https://pinchofyum.com/lo-mein
Ingredients:
    Main:
        Custom: \multicolumn{2}{l}{\textbf{Main}} \\
    Dark Soy Sauce:
        Quantity: 2
        Units: tbsp
    Light Soy Sauce:
        Quantity: 1
        Units: tbsp
    Oyster Sauce:
        Quantity: 3
        Units: tbsp
    Sesame Oil:
        Quantity: 1
        Units: tsp
    Sugar:
        Quantity: 1
        Units: tsp
    Garlic Clove:
        Quantity: 1
        Units: ''
    Ramen Noodles:
        Quantity: 175
        Units: g
    Sesame Oil:
        Quantity: 1
        Units: tbsp
    Green Onions:
        Quantity: 3
        Units: ''
    Veggie Mix:
        Quantity: 200
        Units: g
    Mirrin:
        Quantity: 1 1/2
        Units: tbsp
Preparation:
    - Shake all the sauce ingredients together in a jar.
    - Cook the noodles according to package directions. Drain and set aside.
    - Heat the sesame oil in a large wok or skillet. Add the green onions (white parts) and vegetables to the hot pan. Stir fry until fork-tender, about 5 minutes. Add the mirin to loosen the browned bits up off the bottom of the pan. Add the cooked noodles and about half of the sauce, toss around in the hot pan to combine. Add more sauce if needed (want a medium brown color, not too light, not too dark). Serve topped with remaining green onions!
